 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/insta_items", type: :request do
  
  # InstaItem. As you add validations to InstaItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      InstaItem.create! valid_attributes
      get insta_items_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      insta_item = InstaItem.create! valid_attributes
      get insta_item_url(insta_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_insta_item_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      insta_item = InstaItem.create! valid_attributes
      get edit_insta_item_url(insta_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new InstaItem" do
        expect {
          post insta_items_url, params: { insta_item: valid_attributes }
        }.to change(InstaItem, :count).by(1)
      end

      it "redirects to the created insta_item" do
        post insta_items_url, params: { insta_item: valid_attributes }
        expect(response).to redirect_to(insta_item_url(InstaItem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new InstaItem" do
        expect {
          post insta_items_url, params: { insta_item: invalid_attributes }
        }.to change(InstaItem, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post insta_items_url, params: { insta_item: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested insta_item" do
        insta_item = InstaItem.create! valid_attributes
        patch insta_item_url(insta_item), params: { insta_item: new_attributes }
        insta_item.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the insta_item" do
        insta_item = InstaItem.create! valid_attributes
        patch insta_item_url(insta_item), params: { insta_item: new_attributes }
        insta_item.reload
        expect(response).to redirect_to(insta_item_url(insta_item))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        insta_item = InstaItem.create! valid_attributes
        patch insta_item_url(insta_item), params: { insta_item: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested insta_item" do
      insta_item = InstaItem.create! valid_attributes
      expect {
        delete insta_item_url(insta_item)
      }.to change(InstaItem, :count).by(-1)
    end

    it "redirects to the insta_items list" do
      insta_item = InstaItem.create! valid_attributes
      delete insta_item_url(insta_item)
      expect(response).to redirect_to(insta_items_url)
    end
  end
end
